### ISSUE TITLE
maplibre_ios 0.3.5: build fails on Xcode 16.2 / Swift 6 — pre-generated ObjC header conflicts with compiler-generated interfaces

### ISSUE THREAD

**Issue by pieteroskam** [josxha/flutter-maplibre#514]
## Description

`maplibre_ios 0.3.5` fails to build on Xcode 16.2 (Swift 6.0.3) due to the pre-generated ObjC bridging header `MapLibreIos.h`.

## Environment

- Xcode 16.2 / Swift 6.0.3
- Flutter 3.x (stable)
- maplibre: ^0.3.5 (maplibre_ios 0.3.5)

## Problem

The Swift 6 compiler automatically generates ObjC interfaces for `NSObject` subclasses that conform to `@objc` protocols (like `FlutterPlugin`). The pre-generated `MapLibreIos.h` header also contains ObjC interface declarations for classes like `Helpers`, `MapLibreRegistry`, and `FlutterApi`.

This results in **duplicate interface definitions** at compile time — the compiler's auto-generated interfaces conflict with the ones in `MapLibreIos.h`.

Additionally, `MapLibrePlugin` was included in the pre-generated header in `0.3.4+1` but is **missing** in `0.3.5`, which causes a separate "undeclared identifier" error.

There is also a **trailing comma** in `MapLibreViewFactory.swift:26` (`initStyle: args as! String,`) which is incompatible with the `swift_version = '5.0'` declared in the podspec (trailing commas require Swift 5.9+).

## Errors encountered

```
// Error 1: trailing comma (when swift_version = 5.0)
Swift Compiler Error: Unexpected ',' separator
MapLibreViewFactory.swift:26:8

// Error 2: missing MapLibrePlugin (new in 0.3.5)
Semantic Issue: Use of undeclared identifier 'MapLibrePlugin'
GeneratedPluginRegistrant.m:54:3

// Error 3: duplicate interfaces (when adding MapLibrePlugin back)
Swift Compiler Error: Duplicate interface definition for class 'MapLibrePlugin'
MapLibreIos.h
```

## Workaround

Comment out the `MapLibreIos.h` import in the umbrella header via a Podfile post_install hook. This lets the Swift compiler generate the ObjC interfaces itself:

```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end

  # Fix: pre-generated ObjC header conflicts with Swift 6 auto-generated interfaces
  umbrella = File.join(installer.sandbox.root, 'Target Support Files', 'maplibre_ios', 'maplibre_ios-umbrella.h')
  if File.exist?(umbrella)
    content = File.read(umbrella)
    content.gsub!('#import "MapLibreIos.h"', '// #import "MapLibreIos.h"')
    File.write(umbrella, content)
  end
end
```

## Suggested fix

Remove the pre-generated `MapLibreIos.h` header entirely. Other Flutter Swift plugins (e.g. `shared_preferences_foundation`) don't use one — they rely on the Swift compiler to generate ObjC interfaces automatically, which works across all Xcode versions.

**Comment by josxha** [comment]
Thanks for looking into this @pieteroskam.
Is it correct that you are running the package with CocoaPods? If you [activate SwiftPM](https://docs.flutter.dev/packages-and-plugins/swift-package-manager/for-app-developers) in your project, the package should compile fine. `flutter config --enable-swift-package-manager`
`MapLibreIos.h` is used for ffigen and our custom swift interop solution until [swiftgen](https://pub.dev/packages/swiftgen) becomes a more mature solution. But we might be able to git ignore it and if that gives us backwards compatebility with CocoaPods that would be great.

**Comment by pieteroskam** [comment]
Thanks @josxha  This solved the issue.
